### ISSUE TITLE
Bug report: Consent to process model data reverts to "No"

### ISSUE THREAD

**Issue by starfetch** [freesewing/freesewing#1042]
The consent to process model data in account/actions reverts to `No` upon reload of the account; the "People" and "Pattern" sites show only a blank page, even if consent is set (temporarily) to `Yes`. 

[System info: logged in via Github, Firefox Version 78.10.0esr (64-bit), Debian 10]

**Comment by starfetch** [comment]
Update: After multiple reloads, browser restarts, the consent is set to `No`, but people are accessible and patterns can be drafted from measurements (which should not be possible without consent?).

**Comment by starfetch** [comment]
Update: This bug keeps persisting, but setting the consent back to `Yes` ***and*** allowing open data allows me to access `people`.

**Comment by joostdecock** [comment]
Should be fixed in https://github.com/freesewing/freesewing.org/commit/e905eada9b1fed5582c1367d33cc527168154869

Deploy is building now, please re-open if it ain't so (got to log off now)

**Comment by starfetch** [comment]
@joostdecock I'm sorry to say that I'm re-opening this since bug is still there, a (seemingly random) combination of checking `yes` and reloading my account let's me access `people` again. (Maybe related: the patterns I already created are gone too -- I don't mind at the moment, but that's also not expected behaviour.)

**Comment by joostdecock** [comment]
Can you check again? I'm cautiously optimistic that this time around, it should be ok ;)

**Comment by starfetch** [comment]
I don't know what exactly fixed it, but now the bug is gone for me. Closing :slightly_smiling_face:
