### ISSUE TITLE
[bug]: [v3] Simone always resulting in errors in localhost lab

### ISSUE THREAD

**Issue by BenJamesBen** [freesewing/freesewing#2845]
### What seems to be the problem? 🤔

The Simone design is no longer generating patterns in the `develop` localhost lab. Instead, it always results in errors, starting with:
```
Unable to draft part simone.fbaFront (set 0)
TypeError: 'set' on proxy: trap returned falsish for property 'bustSideCut1'
```

There is always a `Tried to access measurements.bust but it is undefined` warning message, suggesting that Simone is somehow not accessing `plugin-bust`. However, the debug logs indicate that `plugin-bust` is being loaded.

Simone was previously working, so the design itself is likely to be fine. Instead, the problem seems to be the result of a recent change in core infrastructure. Carlita also seems to be having similar issues trying to draw its Front part.

### Are you a FreeSewing patron? 😃

No, I am not 😞

**Comment by joostdecock** [comment]
Fixed

**Comment by BenJamesBen** [comment]
I am still seeing the same error and the same error and warning messages with Simone. However, I will hold off on re-opening this Issue until after all the plugins have been converted. It might be that one of the unconverted plugins is causing the problem.

Carlita is also still having problems, with the same `Tried to access measurements.bust but it is undefined` warning message seen. (However, interestingly Carlita displays no error messages in its Logs even though there is an error when drafting the pattern.)
