### ISSUE TITLE
Logged out when loading some pattern creation pages

### ISSUE THREAD

**Issue by e-matteson** [freesewing/freesewing#806]
**What seems to be the problem?**

Hello! I'm unable to create custom patterns for certain designs. This is what I'm doing:

- Log in (with google)
- Navigate to the Designs list
- Click on the Benjamin design
- Click on "New Benjamin Pattern". The page doesn't load and only shows a white screen.
- If I reload, the page loads and asks me choose a size. However, I am now logged out and can't use my custom measurements.
- If I click any link on the page, such as a size, "Log In", or "Blog", the page doesn't actually change until I reload again. 

I tried this with several designs. Benjamin, Bruce and Florence have the problem I described. Aaron, Albert, Bella, Bent, Breanna, Diana and Brian work correctly.

**Are you a FreeSewing patron?**

 - [x ] Yes, I am :hugs:
 - [ ] No, I am not :thinking:

**Additional context**

Firefox 74, Linux

**Comment by joostdecock** [comment]
Hi, thanks for letting us know you're having some trouble.

We deployed an update earlier, perhaps you're experiencing some issues due to what's cached from the previous deploy and the new code.

Could you try a hard reload (hold the shift key while clicking the reload icon in Firefox)? That should force a cache update so we can rule that out as a parameter.

Please let me know how that goes / whether it solves your issues.

**Comment by e-matteson** [comment]
Hi Joost - hard reloading didn't help, and the problem still happens in a fresh firefox profile. Please let me know if there are other ways I can help debug.

**Comment by joostdecock** [comment]
Could you share your username on the site? That would allow some further digging.

**Comment by joostdecock** [comment]
Ping

**Comment by joostdecock** [comment]
Received username via email, but was unable to reproduce this when impersonating the user.

Asked @e-matteson to check the browser console for errors.

**Comment by e-matteson** [comment]
I don't see anything in the browser console when loading or reloading a broken pattern creation page. There's a 404 error when I first log in - it briefly shows me the robot 404 image, but then correctly shows the account page:
```
GET https://en.freesewing.org/login/callback/602837d1c896de1a6882d84f/gcdhjhqocqibxgsqnaup
[HTTP/2 404 Not Found 337ms]
```
I noticed your screenshot shows an Aaron pattern - that's one of the patterns that works for me. Did you try one of the ones that doesn't work for me, like Benjamin?

Also, I replicated this problem on another computer: firefox 84 on linux.

**Comment by e-matteson** [comment]
I found another broken page: https://en.freesewing.org/account/people/
When I first click the link, I see a blank white page. When I reload, the page says `Start by adding measurements - You haven't added any measurements` (but I have added measurements before). The top item in the sidebar is `Log In`, and nothing happens when I click any links on the page.

Thank you for looking into this stuff!

**Comment by e-matteson** [comment]
Oh here's another example. When I go to a pattern creation page that does work (like Aaron), and then click one of my saved people, it shows me a blank white page with this URL: https://en.freesewing.org/account/people/gevfs
When I reload, it shows me a 404 page and nothing happens when I click any of the links on the page.

**Comment by joostdecock** [comment]
I suspect this is a mismatch between the domain in your local storage and the URL.

Can you try https://freesewing.org/account/people/ instead of https://en.freesewing.org/account/people/ (without the language-specific `en.` subdomain)

**Comment by darigovresearch** [comment]
@e-matteson did the above manage to solve the problem?

**Comment by joostdecock** [comment]
Stale. Closing
